---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-deployment
  namespace: job-demo
spec:
  replicas: 2
  selector:
    matchLabels:
      app: flask
  template:
    metadata:
      labels:
        app: flask
    spec:
      containers:
      - name: flask
        image: anestesia01/k8s-demo:k8s-demo-job_2.0
        ports:
        - containerPort: 8000
        env:
        - name: DATABASE_URL
          value: "postgresql://postgres:password@postgres-service:5432/postgres"

---
apiVersion: v1
kind: Service
metadata:
  name: flask-service
  namespace: job-demo
spec:
  selector:
    app: flask
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
  type: ClusterIP
