---
apiVersion: v1
kind: Pod
metadata:
  name: first-pod
  labels:
    team: backend
spec:
  containers:
  - name: redis-01
    image: redis

---
apiVersion: v1
kind: Pod
metadata:
  name: second-pod
  labels:
    team: backend
spec:
  containers:
  - name: nginx-01
    image: nginx:alpine
  affinity:
    podAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
      - labelSelector:
          matchExpressions:
          - key: team
            operator: In
            values:
            - backend
        topologyKey: "kubernetes.io/hostname"
