def remote = [:]

pipeline {
  agent { label 'docker' }
  parameters {
    gitParameter(type: 'PT_BRANCH', name: 'BRANCH', branchFilter: 'origin/(.*)', defaultValue: 'main', selectedValue: 'DEFAULT')
  }

  environment {
    DOCKER_REPO="anestesia01/jenkins-filiz"
    DOCKER_TOKEN=credentials('docker_repo_token')
    GIT_URL="git@github.com:AnastasiyaGapochkina01/dos-29-k8s.git"
    PRJ_NAME="time-app"
    HOST="89.169.169.167"
  }

  stages {
    stage('Checkout') {
      steps {
        git branch: "${params.BRANCH}", url: "${env.GIT_URL}"
      }
    }

    stage('Build image') {
      steps {
        script {
          sh """
            docker build -t "${env.DOCKER_REPO}:${env.PRJ_NAME}-${BUILD_NUMBER}" ./less_44/time-app
          """
        }
      }
    }

    stage('Push image') {
      steps {
        script {
          sh """
            docker login -u anestesia01 -p "${env.DOCKER_TOKEN}"
            docker push "${env.DOCKER_REPO}:${env.PRJ_NAME}-${BUILD_NUMBER}"
          """
        }
      }
    }

    stage('Prepare credentials'){
      steps {
        withCredentials([sshUserPrivateKey(credentialsId: 'worker-02', keyFileVariable: 'private_key', usernameVariable: 'username')]) {
          script {
            remote.name = "${env.HOST}"
            remote.host = "{env.HOST}"
            remote.name = "$username"
            remote.identity = readFile "$private_key"
            remote.allowAnyHosts = true
          }
        }
      }
    }

    stage('Deploy') {
      steps {
        script {
          sshCommand remote: remote, command: """
            docker pull "${env.DOCKER_REPO}:${env.PRJ_NAME}-${BUILD_NUMBER}"
            docker stop "${env.PRJ_NAME}" || true
            docker rm "${env.PRJ_NAME}" || true
            docker run -d -it --name "${env.PRJ_NAME}" "${env.DOCKER_REPO}:${env.PRJ_NAME}-${BUILD_NUMBER}"
          """
        }
      }
    }
  }
}
