apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.db.service }}
  namespace: {{ .Values.namespace | default "default" }}
spec:
  selector:
    app: postgres
  ports:
    - port: {{ .Values.db.port }}
      targetPort: {{ .Values.db.port }}
      protocol: TCP

