apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: metrics-db-statefulset
  namespace: {{ .Values.namespace | default "default" }}
spec:
  selector:
    matchLabels:
      app: postgres
  replicas: 1
  serviceName: {{ .Values.db.service }}
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
      - name: postgres
        image: {{ .Values.db.image }}
        ports:
          - containerPort: {{ .Values.db.port }}
        env:
        - name: POSTGRES_DB
          valueFrom:
            secretKeyRef:
              name: db-secret
              key: DB_NAME
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: db-secret
              key: DB_USER
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-secret
              key: DB_PASSWORD

